import { ExtensionConfig } from "./types";

export const SUPPORTED_EXTENSIONS: ExtensionConfig[] = [
  {
    ext: "pdf",
    label: ".PDF",
    color: "#ef4444",
    badgeBg: "bg-red-500/10",
    badgeBorder: "border-red-500/30",
    badgeText: "text-red-400",
    desc: "Adobe Portable Document Format",
  },
  {
    ext: "epub",
    label: ".EPUB",
    color: "#10b981",
    badgeBg: "bg-emerald-500/10",
    badgeBorder: "border-emerald-500/30",
    badgeText: "text-emerald-400",
    desc: "Electronic Publication (Standard E-Book)",
  },
  {
    ext: "zip",
    label: ".ZIP",
    color: "#3b82f6",
    badgeBg: "bg-blue-500/10",
    badgeBorder: "border-blue-500/30",
    badgeText: "text-blue-400",
    desc: "Zip Archive (Source Code & E-Book Bundles)",
  },
  {
    ext: "mobi",
    label: ".MOBI",
    color: "#f59e0b",
    badgeBg: "bg-amber-500/10",
    badgeBorder: "border-amber-500/30",
    badgeText: "text-amber-400",
    desc: "Mobipocket E-Book (Kindle Format)",
  },
  {
    ext: "cbz",
    label: ".CBZ",
    color: "#8b5cf6",
    badgeBg: "bg-purple-500/10",
    badgeBorder: "border-purple-500/30",
    badgeText: "text-purple-400",
    desc: "Comic Book Zip Archive",
  },
  {
    ext: "cbr",
    label: ".CBR",
    color: "#ec4899",
    badgeBg: "bg-pink-500/10",
    badgeBorder: "border-pink-500/30",
    badgeText: "text-pink-400",
    desc: "Comic Book RAR Archive",
  },
  {
    ext: "djvu",
    label: ".DJVU",
    color: "#06b6d4",
    badgeBg: "bg-cyan-500/10",
    badgeBorder: "border-cyan-500/30",
    badgeText: "text-cyan-400",
    desc: "DjVu Document Format",
  },
  {
    ext: "azw3",
    label: ".AZW3",
    color: "#f97316",
    badgeBg: "bg-orange-500/10",
    badgeBorder: "border-orange-500/30",
    badgeText: "text-orange-400",
    desc: "Amazon Kindle Format 8",
  },
  {
    ext: "rar",
    label: ".RAR",
    color: "#a855f7",
    badgeBg: "bg-purple-500/10",
    badgeBorder: "border-purple-500/30",
    badgeText: "text-purple-400",
    desc: "RAR Archive Format",
  },
  {
    ext: "7z",
    label: ".7Z",
    color: "#6366f1",
    badgeBg: "bg-indigo-500/10",
    badgeBorder: "border-indigo-500/30",
    badgeText: "text-indigo-400",
    desc: "7-Zip Compressed Archive",
  },
  {
    ext: "txt",
    label: ".TXT",
    color: "#64748b",
    badgeBg: "bg-slate-500/10",
    badgeBorder: "border-slate-500/30",
    badgeText: "text-slate-400",
    desc: "Plain Text Document",
  },
  {
    ext: "docx",
    label: ".DOCX",
    color: "#0284c7",
    badgeBg: "bg-sky-500/10",
    badgeBorder: "border-sky-500/30",
    badgeText: "text-sky-400",
    desc: "Microsoft Word Document",
  },
];
